name: nuxt-app CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash
    working-directory: nuxt-app/

jobs:
  ci:
    name: Build and test nuxt-app
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 18.12.1
        package-manager:
          - yarn

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.2.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: ${{ matrix.package-manager }}

      - name: Lint project
        run: ${{ matrix.package-manager }} lint

      - name: Test project
        run: ${{ matrix.package-manager }} test
